# Generated by Django 4.2.4 on 2023-10-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=250, null=True, verbose_name='Descripcion')),
                ('image', models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen')),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
