# Generated by Django 4.2.4 on 2023-10-01 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0002_articulos_delete_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='image',
            new_name='imagen',
        ),
    ]
